#// SPDX-License-Identifier: blessing
#// d a r k s h a p e s
"""
## module table of contents

#### [nnll_00 - deepest_key_of](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_00/src.py)
#### [nnll_01 - key_trail](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_01/src.py)
#### [nnll_04 - metadata_from_safetensors](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_04/src.py)
#### [nnll_05 - create_llama_parser, metadata_from_gguf, gguf_check](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_05/src.py)
#### [nnll_06 - compare_dicts](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_06/src.py)
#### [nnll_07 - add_architecture, to_dict, of, Component, structure, add_component, Architecture](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_07/src.py)
#### [nnll_08 - hard_random, soft_random](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_08/src.py)
#### [nnll_09 - encode_prompt](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_09/src.py)
#### [nnll_13 - SystemCapacity, optimal_config, detect_capacity](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_13/src.py)
#### [nnll_16 - variables, attribute, configure, Backend](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_16/src.py)
#### [nnll_17 - CUDADevice, OPENVINODevice, MPSDevice, XPUDevice, DMLDevice, configure, contains](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_17/src.py)
#### [nnll_18 - get_pipeline_embeds](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_18/src.py)
#### [nnll_22 - create_symlink, get_folder_name, AbstractLink, TextEncoderLink, _add_link, UNetLink, AutoencoderLink, get_filename](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_22/src.py)
#### [nnll_23 - load_method, call_method, DynamicMethodConstructor](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_23/src.py)
#### [nnll_24 - pull_key_names, sink_into, KeyTrail](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_24/src.py)
#### [nnll_25 - ExtractAndMatchMetadata, is_pattern_in_layer](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_25/src.py)
#### [nnll_26 - random_int_from_gpu, random_tensor_from_gpu](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_26/src.py)
#### [nnll_27 - wipe_printer, pretty_tabled_output](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_27/src.py)
#### [nnll_28 - metadata_from_pickletensor](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_28/src.py)
#### [nnll_29 - filter_metadata, LayerFilter](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_29/src.py)
#### [nnll_30 - write_json_file, read_json_file](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_30/src.py)
#### [nnll_31 - count_tensors_and_extract_shape, find_files_with_pattern, find_entry](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_31/src.py)
#### [nnll_32 - coordinate_header_tools](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_32/src.py)
#### [nnll_33 - ValueComparison, check_model_identity](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_33/src.py)
#### [nnll_34 - detect_index_sequence, gather_sharded_files](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_34/src.py)
#### [nnll_35 - capture_title_numeral](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_35/src.py)
#### [nnll_36 - read_state_dict_headers](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_36/src.py)
#### [nnll_37 - index, collect_file_headers_from](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_37/src.py)
#### [nnll_38 - extract_tensor_data, ExtractValueData](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_38/src.py)
#### [nnll_39 - parse_model_header](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_39/src.py)
#### [nnll_40 - create_model_tag](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_40/src.py)
#### [nnll_41 - trace_file_structure](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_41/src.py)
#### [nnll_42 - populate_module_index](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_42/src.py)
#### [nnll_43 - ](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_43/src.py)
#### [nnll_44 - compute_file_hash](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_44/src.py)
#### [nnll_45 - download_hub_file](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_45/src.py)
"""
