### <!-- // /*  SPDX-License-Identifier: blessing) */ -->
### <!-- // /*  d a r k s h a p e s */ -->
## module table of contents

"""
#### [nnll_01 - name, readout, wrapper, debug_message, debug_monitor, info_monitor](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_01/src.py)
#### [nnll_04 - metadata_from_safetensors](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_04/src.py)
#### [nnll_05 - attempt_file_open, metadata_from_gguf, create_gguf_reader, gguf_check, create_llama_parser](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_05/src.py)
#### [nnll_07 - of, add_component, Component, add_architecture, to_dict, Architecture, structure](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_07/src.py)
#### [nnll_08 - soft_random, hard_random, seed_planter](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_08/src.py)
#### [nnll_09 - encode_prompt](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_09/src.py)
#### [nnll_18 - get_pipeline_embeds](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_18/src.py)
#### [nnll_22 - AbstractLink, create_symlink, AutoencoderLink, UNetLink, _add_link, TextEncoderLink, get_filename, get_folder_name](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_22/src.py)
#### [nnll_24 - sink_into, pull_key_names, KeyTrail](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_24/src.py)
#### [nnll_25 - is_pattern_in_layer, ExtractAndMatchMetadata](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_25/src.py)
#### [nnll_26 - random_int_from_gpu, random_tensor_from_gpu](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_26/src.py)
#### [nnll_27 - wipe_printer, pretty_tabled_output](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_27/src.py)
#### [nnll_28 - metadata_from_pickletensor](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_28/src.py)
#### [nnll_29 - identify_layer_type, finalize_metadata, reference_walk_conductor, LayerFilter](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_29/src.py)
#### [nnll_30 - write_json_file, read_json_file](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_30/src.py)
#### [nnll_31 - count_tensors_and_extract_shape, find_files_with_pattern, find_entry](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_31/src.py)
#### [nnll_32 - coordinate_header_tools](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_32/src.py)
#### [nnll_33 - check_inner_values, ValueComparison, check_model_identity](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_33/src.py)
#### [nnll_34 - gather_sharded_files, detect_index_sequence](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_34/src.py)
#### [nnll_35 - capture_title_numeral](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_35/src.py)
#### [nnll_36 - read_state_dict_headers](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_36/src.py)
#### [nnll_37 - index, collect_file_headers_from](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_37/src.py)
#### [nnll_39 - route_metadata, gather_metadata](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_39/src.py)
#### [nnll_40 - create_model_tag](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_40/src.py)
#### [nnll_41 - trace_file_structure](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_41/src.py)
#### [nnll_42 - populate_module_index](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_42/src.py)
#### [nnll_43 - ](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_43/src.py)
#### [nnll_44 - collect_hashes, retrieve_remote_hash, compute_hash_for](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_44/src.py)
#### [nnll_45 - download_hub_file](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_45/src.py)
#### [nnll_46 - identify_layer_type, identify_model, IdConductor, identify_category_type](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_46/src.py)
#### [nnll_47 - NodeNames, BracketedDict, drop_tuple, UpField, ListOfDelineatedStr, ExtensionType, bracket_check, NodeWorkflow, DownField, EmptyField, IsThisNode, NodeDataMap](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_47/src.py)
#### [nnll_48 - read_header, read_txt_contents, read_jpg_header, read_png_header, MetadataFileReader, read_schema_file](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_48/src.py)
#### [nnll_49 - extract_prompts, make_paired_str_dict, arrange_exif_metadata, coordinate_metadata_operations, extract_dict_by_delineation, clean_with_json, remove_esc_codes, validate_typical, filter_keys_of, delineate_by_esc_codes, arrange_webui_metadata, validate_mapping_bracket_pair_structure_of, arrange_str_metadata, arrange_nodeui_metadata, search_for_prompt_in, parse_metadata, redivide_nodeui_data_in, filter_exif_keys_in, arrange_dict_metadata, repair_flat_dict, search_for_gen_data_in](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_49/src.py)
#### [nnll_51 - insert_into_db, create_table, managed_connection, retrieve_from_db, save_user_set_to_db](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_51/src.py)
#### [nnll_52 - ](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_52/src.py)
#### [nnll_53 - add_to_metadata, add_to_undo, sdxl_pipe](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_53/src.py)
#### [nnll_54 - read_metadata_from, ModelTool](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_54/src.py)
#### [nnll_56 - add_hi_diffusion, dynamo_compile, add_ays, add_generator](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_56/src.py)
#### [nnll_57 - write_to_disk, save_element](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_57/src.py)
#### [nnll_59 - name_save_file_as, form_metadata, write_image_to_disk](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_59/src.py)
#### [nnll_60 - decorator, wrapper, docstring_demo_func, _load_cache, update_cache, JSONCache, _save_cache, refresh](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_60/src.py)
#### [nnll_61 - from_dict, create_timestamp, synthesize_genesis_block, create, __post_init__, load_chain_from_file, Block, save_chain_to_file, to_dict, is_chain_valid, HyperChain, calculate_hash, add_block](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_61/src.py)
#### [nnll_62 - ConstructPipeline, wrapper, create_pipeline, add_lora, pipe_call](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_62/src.py)
#### [nnll_63 - euler_a, add_generator, ddim, add_ays, dpmpp, dynamo_compile, add_hi_diffusion, get_func_name](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_63/src.py)
#### [nnll_64 - run_inference](/Users/unauthorized/Documents/GitHub/darkshapes/nnll/modules/nnll_64/src.py)
"""
